# Generated by Django 5.0 on 2023-12-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                default="FEMALE",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("EMPLOYEE", "EMPLOYEE"),
                    ("USER", "USER"),
                ],
                max_length=8,
            ),
        ),
    ]
