# Generated by Django 5.0 on 2023-12-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_account_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
            ],
        ),
    ]
