# Generated by Django 5.0 on 2023-12-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0005_subcategory_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="cms.category"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
