# Generated by Django 5.0 on 2023-12-30 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0006_alter_product_sub_category_category_parent_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sub_category",
            new_name="category",
        ),
    ]
