# Generated by Django 5.0 on 2023-12-30 05:26

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0007_rename_sub_category_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name="SanPhamSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="cms.product"
                    ),
                ),
                (
                    "size",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="cms.size"
                    ),
                ),
            ],
        ),
    ]
