# Generated by Django 5.0 on 2023-12-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_remove_order_size_productorder_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
