# Generated by Django 5.0 on 2024-01-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0014_order_paymentstatus_order_paymenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="orderPartnerId",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
